version: "2"

run:
  timeout: 10m

linters:
  enable:
    - asciicheck
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - unconvert
    - unused
    - staticcheck 
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling 
  settings:
    revive:
      rules:
        - name: dot-imports
          arguments:
            - allowedPackages:
              - "github.com/onsi/ginkgo"
              - "github.com/onsi/ginkgo/v2"
              - "github.com/onsi/gomega"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: false

linters-settings:
  gosec:
    # Exclude generated files
    exclude-generated: true
