run:
  timeout: 10m
linters:
  enable:
    - asciicheck
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
linters-settings:
  gosec:
    # Exclude generated files
    exclude-generated: true
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  revive:
    rules:
      - name: dot-imports
        arguments:
          - allowedPackages:
              - "github.com/onsi/ginkgo"
              - "github.com/onsi/ginkgo/v2"
              - "github.com/onsi/gomega"