# Configuration for CRD Reference Documentation Generator (crd-ref-doc)
##  go run github.com/elastic/crd-ref-docs@v0.1.0 --config docs/config.yaml --renderer=markdown --output-path ./docs/api-reference.md --source-path=apis
processor:
  ignoreTypes:
    - ".*List$"
    - ".*Status$"
  ignoreFields:
    - "status$"
    - "TypeMeta$"
render:
  kubernetesVersion: 1.32